Move ui to /filing/
cfpb/hmda-platform-ui pull request #1069
Opened 2018-05-11 23:45 UTC by wpears

Updates app to no longer expect to live at `/`

Depends on #1068

2018-05-16 15:34 UTC, awolfe76 requested changes

2018-05-16 15:34 UTC, awolfe76 commented on src/common/Header.jsx
> +        <a href={window.HMDA_ENV.HOMEPAGE_URL} className="usa-nav-link">
I'm not sure we want to include the entire navigation within the filing app.

I'm not completely against it, we had talked about having the app be a sort-of-separate thing altogether, even applying slightly different styling to it (at some point).

Also, within the app as it is today the "Home" link takes you back to the filing app home page (the institutions listing), with these updates it would now take you to the overall home page.

I think it would be more intuitive to someone filing to not have these links to be able to focus on the filing itself, which is what they would want to do once here.

(Keeping the home link of course.)

I think `/filing/`, **when logged out**, would show all the links. But when logged in have them removed. With some other minor changes we can make this pretty clear.

@designlanguage

2018-05-16 15:34 UTC, awolfe76 commented on src/common/Header.jsx
> +              <img src="/filing/img/ffiec-logo.png" height="27px" alt="FFIEC" />
Should we update the content here to be "HMDA Filing Platform" or "HMDA Filing"?

2018-05-16 15:34 UTC, awolfe76 commented on src/common/Footer.jsx
>                <li className="usa-footer-primary-content">
We also talked about removing a lot of the content from the footer. Again, since someone in the filing app is likely there to do that single task having all of these links available (which are used prior to filing) doesn't seem to help.

We probably should update the other "sites" footers to use this one and update this one to use the other footer.

#### Other footer (eg, pub-ui)

![new-footer](https://user-images.githubusercontent.com/2932572/40119584-117f8ca0-58eb-11e8-9353-d941931011f8.png)

2018-05-16 15:34 UTC, awolfe76 commented on src/index.html
>                      Filers who wish to confirm that their LAR is formatted in
I think we can remove the FAQs section completely. This content would better in a different place.

@keileyo @colleenms - can we also remove the [Notice and Consent Banner and PRA statement](https://github.com/cfpb/hmda-platform-ui/pull/1069/files#diff-e249faefed5757034596c5096d33dab6R124) from this page? It will be on the new homepage. Just not sure if one place is enough or if we need it in both.

2018-05-16 16:28 UTC, wpears commented on src/common/Header.jsx
> +        <a href={window.HMDA_ENV.HOMEPAGE_URL} className="usa-nav-link">
Yeah my logic here was that the changed header link on the left still goes to the `/filing/` home along with the `/filing/` link itself and I didn't want to switch the meaning of what "home" meant without also changing the designs.

We did discuss changing the nav look entirely, but I didn't want to do that in this PR to instead focus on getting the hmda-homepage and `/filing/` changes working.

2018-05-16 16:29 UTC, wpears commented on src/common/Header.jsx
> +              <img src="/filing/img/ffiec-logo.png" height="27px" alt="FFIEC" />
Possibly! I'd be for either.

2018-05-18 12:15 UTC, awolfe76 commented on src/common/Footer.jsx
>                <li className="usa-footer-primary-content">
#1072 will take care of this.

2018-05-18 12:16 UTC, awolfe76 commented on src/common/Header.jsx
> +        <a href={window.HMDA_ENV.HOMEPAGE_URL} className="usa-nav-link">
Based on the earlier conversation we should remove this change. We won't have all of the navigation within the filing application.

2018-05-18 12:18 UTC, awolfe76 commented on src/common/Header.jsx
> +              <img src="/filing/img/ffiec-logo.png" height="27px" alt="FFIEC" />
We can make this quick update too.

2018-05-18 12:36 UTC, keileyo commented on src/index.html
>                      Filers who wish to confirm that their LAR is formatted in
PRA & notice and consent need to be on the filing application page. i am down to remove FAQs.

2018-05-22 16:14 UTC, awolfe76 approved these changes

2018-05-22 16:14 UTC, merged