Convert remaining institutionId references and uses of institution.id
cfpb/hmda-platform-ui pull request #1204
Opened 2018-12-10 18:40 UTC by wpears

Closes #1103

2018-12-11 12:06 UTC, awolfe76 requested changes
I think there are just a few more places where the `id -> lei` switch would help.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/fetchCSV.js
> +      id: lei,
Should we pass this as `lei: lei` too?

If so, we'd need to update [`makeUrl`](https://github.com/cfpb/hmda-platform-ui/blob/393ab2cc9497be3e5345f3) too. And `makeUrl` has some [commented out `env` stuff](https://github.com/cfpb/hmda-platform-ui/blob/393ab2cc9497be3e5345f328eb99f9f74ed61f7b/src/api/makeUrl.js#L2-L6) in it that we can remove.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/fetchIRSCSV.js
> +      id: lei,
Same as above, `id -> lei`.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/fetchNewSubmission.js
> +    const id = appState.lei
`const lei` here too.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/fetchNewSubmission.js
> +    const id = appState.lei
And if so, [line 18](https://github.com/cfpb/hmda-platform-ui/pull/1204/files#diff-22717cca12596cbafadf42630682809bR18) 👇 would need to be updated.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/processFileErrors.js
> +    const id = getState().app.lei
`id -> lei`

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/requestUpload.js
> +      id: getState().app.lei
Same here, but then the upload reducer would need updated too.

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/selectFile.js
> +    const id = getState().app.lei
`lei -> id`

2018-12-11 12:06 UTC, awolfe76 commented on src/actions/selectNewFile.js
> +      id: getState().app.lei
`id -> lei`

2018-12-11 12:06 UTC, awolfe76 commented on src/api/fetch.js
> +    id: appState.lei,
`id -> lei`

2018-12-11 12:06 UTC, awolfe76 commented on src/modals/confirmationModal/container.jsx
> +  const id = state.app.lei
`id -> lei`

2018-12-11 12:06 UTC, awolfe76 commented on src/submission/upload/container.jsx
> +  const id = state.app.lei
`id -> lei`

2018-12-11 18:11 UTC, wpears commented
:+1:

2018-12-12 14:22 UTC, awolfe76 commented on src/modals/confirmationModal/container.jsx
> +    lei,
This `lei` update requires changes to [`confirmationModal/index.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/393ab2cc9497be3e5345f328eb99f9f74ed61f7b/src/modals/confirmationModal/index.jsx#L49) too.

2018-12-12 14:23 UTC, awolfe76 commented on src/modals/confirmationModal/container.jsx
> +    lei,
Its causing

```
TypeError: Cannot read property 'focus' of undefined
ModalConfirm._focusButton
src/modals/confirmationModal/index.jsx:8
   5 | import '../Modal.css'
   6 | 
   7 | let _focusButton = function() {
>  8 |   return this.confirmButton.focus()
   9 | }
  10 | 
  11 | let _focusLink = function() {
```

2018-12-12 23:56 UTC, awolfe76 approved these changes

2018-12-12 23:56 UTC, merged