Increase coverage
cfpb/hmda-platform-ui pull request #510
Opened 2017-04-26 20:53 UTC by wpears

Reorganizes some stray files and pulls several small modules out of `api.js` for testing.

2017-04-27 19:17 UTC, awolfe76 requested changes
I like what you did with the `utils`, but are there more tests coming in a few places? The `api`, `fetch`, and `actions` seem be :hurtrealbad: .

2017-04-27 19:17 UTC, awolfe76 commented on __tests__/api/api.js
> +  it('fetches institutions', () => {
More tests coming?

2017-05-05 13:14 UTC, wpears commented
@awolfe76 should be good to go now

2017-05-05 14:12 UTC, awolfe76 approved these changes

2017-05-05 14:12 UTC, merged