Break out the alerts into a component
cfpb/hmda-platform-ui pull request #656
Opened 2017-07-13 17:32 UTC by awolfe76

Closes #633 

Left out the [`UploadForm`](https://github.com/cfpb/hmda-platform-ui/blob/10a3ea35f52169560cada2fdcf0a913376a813a2/src/js/components/UploadForm.jsx) because of the way it [renders the possible list of errors](https://github.com/cfpb/hmda-platform-ui/blob/10a3ea35f52169560cada2fdcf0a913376a813a2/src/js/components/UploadForm.jsx#L23). Any thoughts there?

_Some minor formatting updates._

2017-07-14 17:45 UTC, wpears requested changes

2017-07-14 17:45 UTC, wpears commented on src/js/components/Alert.jsx
> +        {htmlElement ? htmlElement : null} {/* allow for additional html */}
Instead of passing in the custom `htmlElement` prop, you can just use `props.children` and wrap children in standard html.

2017-07-14 17:45 UTC, wpears commented on src/js/components/Alert.jsx
> +        {htmlElement ? htmlElement : null} {/* allow for additional html */}
ie
```
<Alert some={props}>
  <p>Like this</p>
</Alert>
```

2017-07-14 19:38 UTC, wpears commented on src/js/components/Alert.jsx
> +        {children ? children : null}
afaik `props.children` will always either be a valid element or `null`, so you don't need this check here

2017-07-17 14:38 UTC, wpears commented
@awolfe76 so I missed it the first time (somehow), but the method of passing an array of nodes as a prop would require a `key` on each one, which kinda bungles it.

I reimplemented this approach by just cloning the node that Alert wraps with the proper className. This also makes the structure of children more obvious, imo, wrt to how it interacts with the text of the alert (since you're just passing children as children and not as props that get rendered as children).

I did still allow the heading to be specified as a prop, since this allows it to be kept a bit more separate.

2017-07-17 14:38 UTC, wpears approved these changes

2017-07-24 15:04 UTC, awolfe76 commented
👍

2017-07-24 15:04 UTC, merged