Jumping table pagination
cfpb/hmda-platform-ui pull request #708
Opened 2017-08-08 22:34 UTC by wpears

- Little table redesign / cleanup (a little less padding and a lighter rule
- Paging to the last page no longer causes a jump due to some scrollTo hackery

2017-08-10 20:46 UTC, awolfe76 requested changes
Just a few small things here.

2017-08-10 20:46 UTC, awolfe76 commented on src/sass/hmda.scss
> +  padding: 1rem;
What do you think about shrinking this even more? `.75` seems nice too. 
Also, in either case, [this](https://github.com/cfpb/hmda-platform-ui/blob/f6e3368d976fcc78a895c34ecd8b4877326a39a2/src/sass/components/IRSReport.scss#L20) can be removed.
And in the IRS file, we should add `tfoot td` [here](https://github.com/cfpb/hmda-platform-ui/blob/f6e3368d976fcc78a895c34ecd8b4877326a39a2/src/sass/components/IRSReport.scss#L18). I noticed the font size is off there.

2017-08-10 20:46 UTC, awolfe76 commented on src/sass/components/ParseErrors.scss
> +  table td:first-of-type,
👍

2017-08-10 23:21 UTC, wpears commented
@awolfe76 agreed re: padding, just didn't want to make quite so big a change all at once with some eyes on it. Updated.

2017-08-11 12:46 UTC, awolfe76 approved these changes

2017-08-11 12:47 UTC, merged