Update wording to lend a greater sense of completion to signature message
cfpb/hmda-platform-ui pull request #763
Opened 2017-09-11 17:14 UTC by wpears

*ie* signature happiness
<img width="977" alt="screen shot 2017-09-11 at 10 13 07 am" src="https://user-images.githubusercontent.com/1558033/30287438-ec35c190-96d9-11e7-8681-0fa1570f642d.png">

2017-09-12 13:41 UTC, awolfe76 reviewed
LGTM, something does seem off about the multiple font sizes, feels a bit scattered that way.

But would like for @designlanguage and @keileyo to make sure the wording is 👍 .

2017-09-13 14:59 UTC, awolfe76 requested changes
A few things here just to make it feel less "scattered".

#### Example

![signature](https://user-images.githubusercontent.com/2932572/30384543-948dd334-9872-11e7-8b46-f894717f1651.png)

2017-09-13 14:59 UTC, awolfe76 commented on src/js/components/Signature.jsx
> +        <hr/>
I think we'd be ok without the `<hr>` tags in this alert, including the one below. We haven't used them in other alerts and there's not a real change in content here. The messaging is all about filing completion.

2017-09-13 14:59 UTC, awolfe76 commented on src/js/components/Signature.jsx
> +        <p className="usa-text-small">Your submission was received on <strong>{ordinalHour(new Date(timestamp))}</strong>.</p>
I think we should remove the `usa-text-small` class here. The font size jump (from heading to p to small back to p) makes it feel like there's too much going on.

2017-09-13 14:59 UTC, awolfe76 commented on src/js/components/Signature.jsx
> +        <p>Congratulations, you have successfully completed your HMDA filing for {filingPeriod}!</p>
I think we can combine theses paragraph tags making it `<p>Congratulations, you have successfully completed your HMDA filing for {filingPeriod}! Your data and signature have been received and recorded.</p>`.

There doesn't seem like a big need for them to be broken out.

2017-09-13 14:59 UTC, awolfe76 commented on src/js/components/Signature.jsx
> +        <p className="usa-text-small">Your submission was received on <strong>{ordinalHour(new Date(timestamp))}</strong>.</p>
Same as above here, what if we combine these to be `<p>Your submission was received on <strong>{ordinalHour(new Date(timestamp))}</strong> and Your receipt number is <strong>{receipt}</strong>.</p>`.

2017-09-13 16:10 UTC, wpears commented
@designlanguage Thoughts on the above?
The original reason I separated each line was to give each statement more visual weight and to provide the traditional line-item appearance of the receipt.
The horizontal rules were provided for structure and emphasis and the font size changes were to add a bit of hierarchy (normal size: things you should read/know, usa-text-small: errata that may be useful but isn't really essential to read at this time).

2017-09-13 16:26 UTC, designlanguage commented
@wpears - I think we can compress this info a bit.

The message seems to be made up three parts: What, When, and Where. I'm interested to know if any of these are less important, but it seems like more of a progression to me, so I'm for keeping them the same size. If we start a new line for each it could look like this:

### ✔  __HMDA filing submitted__

Congratulations, you successfully completed your HMDA filing for 2017!

Your data and signature were received and recorded on __September 12th, 2017, 1:28:14 pm.__

You will receive an email confirmation shortly at __NameATBank0.com__. Your receipt number for this submission is __00000000-0000000-0000000000000__.

2017-09-14 12:59 UTC, awolfe76 approved these changes

2017-09-14 13:00 UTC, merged